### ISSUE TITLE
Is sleep perfect？

### ISSUE THREAD

**Issue by ixkqo** [IFierta/mac-os-opencore-asus-k501lx_lb#3]
hi，Is your hackintosh normal for long sleep？

**Comment by IFierta** [comment]
> hi，Is your hackintosh normal for long sleep？

Sleep works great. In addition, hibernate works. Download again config.plist. I enabled the "Disable RTC wake scheduling" patch to prevent the Mac from waking up when power nap is enabled.

**Comment by ixkqo** [comment]
After sleeping for about 2 hours, wake up and black screen

**Comment by ixkqo** [comment]
After sleeping for about 2 hours, the black screen wakes up. Have you ever experienced this?

**Comment by IFierta** [comment]
Matrix AU Optronics  B156HTN03.8?

**Comment by ixkqo** [comment]
my computer is k501lx，Monitor AU Optronics B156HTN03.8 
I tested all the ids of my computer sound card alc233, only 33 works.
CodecCommander.kext not installed in /L/E 
the computer sleep and wake up normally,but long time sleep,wake up the screen is black，Unstable, it should be because I did not unlock cfg

**Comment by IFierta** [comment]
> my computer is k501lx，Monitor AU Optronics B156HTN03.8
> the computer sleep and wake up normally,but long time sleep,wake up the screen is black，Unstable, it should be because I did not unlock cfg

black screen on wake up (with AU Optronics B156HTN03.8 monitor) is a known issue. Nobody fixed it. This is a longstanding issue since mac os sierra 10.12.4. Before mac os 10.12.3, the screen woke up normally. The problem is related to the signal transmission from the video driver, which is not supported by the monitor. What's the signal? I dont know. You need to disassemble the driver, look for changes and make a patch.  :)
Maybe it will help you solve the problem by replacing the screen with the lg philips lp156wf6 screen.

Here is one of the topics with this problem.
Check out this topic: [[Unsolvable] Black screen when waking from sleep on Mojave 10.14.3, Lenovo G50-80, Broadwell HD 5500](https://www.tonymacx86.com/threads/unsolvable-black-screen-when-waking-from-sleep-on-mojave-10-14-3-lenovo-g50-80-broadwell-hd-5500.271315/url)


> I tested all the ids of my computer sound card alc233, only 33 works.
> CodecCommander.kext not installed in /L/E

Try CodecCommander.kext installed in /L/E. Then check how your headset works.
Hmm ... interesting. It works for me with layout ID 3 ( alc 233 )

**Comment by IFierta** [comment]
<img width="768" alt="Снимок экрана 2020-08-31 в 20 07 25" src="https://user-images.githubusercontent.com/26610620/91735488-d4d47700-ebc5-11ea-9789-0dbfbccff9b4.png">

**Comment by ixkqo** [comment]
After I added the network card driver to the config.plist file, before entering the oc boot, there are several lines of code appearing, how should I close it
![photo](https://user-images.githubusercontent.com/70495143/91792275-b9aa4b80-ec47-11ea-9264-2fb5471c4843.png)

**Comment by ixkqo** [comment]
<img width="660" alt="voice" src="https://user-images.githubusercontent.com/70495143/91811571-4a8e2080-ec62-11ea-8c27-5813ca12c579.png">

**Comment by ixkqo** [comment]
<img width="660" alt="voice" src="https://user-images.githubusercontent.com/70495143/91811744-92ad4300-ec62-11ea-8e0c-411b60f02445.png">

**Comment by ixkqo** [comment]
When my computer shuts down, stripes appear for a moment
[Uploading ph.jpg …]()

**Comment by IFierta** [comment]
Show me your IORegistry file. (use IORegistryExplorer.app)

**Comment by IFierta** [comment]
>Try CodecCommander.kext installed in /L/E. Then check how your headset works.
Working?

**Comment by ixkqo** [comment]
not good,the headset sound is very small, current sound very strong
[IORegistry.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5154705/IORegistry.zip)

**Comment by IFierta** [comment]
Upload EFI folder for me.

**Comment by IFierta** [comment]
> When my computer shuts down, stripes appear for a moment

what screen resolution is set?

**Comment by ixkqo** [comment]
> > When my computer shuts down, stripes appear for a moment
> 
> what screen resolution is set?
1920x1080
[EFIk501lx.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5155494/EFIk501lx.zip)

**Comment by IFierta** [comment]
<img width="1536" alt="Снимок экрана 2020-09-01 в 15 06 29" src="https://user-images.githubusercontent.com/26610620/91836895-db65fb80-ec64-11ea-9ddc-20de48671410.png">

Layout ID 33 - works perfectly, headphones and sound speakers. Try use MacBookAir7.2. CodecCommander you install in /Library/Extensions ? It is very important that it is installed in this folder.

**Comment by IFierta** [comment]
![Снимок_экрана_2020-09-01_в_15_21_28](https://user-images.githubusercontent.com/26610620/91838647-41538280-ec67-11ea-9ed2-5559eeb2791f.jpg)

**Comment by ixkqo** [comment]
> ![Снимок_экрана_2020-09-01_в_15_21_28](https://user-images.githubusercontent.com/26610620/91838647-41538280-ec67-11ea-9ed2-5559eeb2791f.jpg)
> 
> I am not using this SSDT, so I disabled it. If you're using it, turn it on.

SSDT-BATT-ASUS.aml，What is ssdt related to

**Comment by IFierta** [comment]
SSDT-BATT-ASUS.aml - If the state of charge, the discharge of the battery does not show correctly, corrects the status of the charge and discharge of the battery. If the status is displayed correctly, then this SSDT is not needed.

**Comment by IFierta** [comment]
> <img alt="Снимок экрана 2020-09-01 в 15 06 29" width="1536" src="https://user-images.githubusercontent.com/26610620/91836895-db65fb80-ec64-11ea-9ddc-20de48671410.png">
> 
> Layout ID 33 - works perfectly, headphones and sound speakers. CodecCommander you install in /Library/Extensions ? It is very important that it is installed in this folder. SIP Disabled? csrutil status - check.

??? :)

**Comment by ixkqo** [comment]
yes，T did it

**Comment by IFierta** [comment]
>only bluetooth Cannot be closed.

Bluetooth does not turn off on this card. Change to a compatible card with mac.
Sound in headphones normal work?

**Comment by IFierta** [comment]
> > When my computer shuts down, stripes appear for a moment
> 
> what screen resolution is set?
> 1920x1080

[Enable macOS HiDPI](https://github.com/xzhih/one-key-hidpi)

Use the script to set a more user-friendly resolution. Set the resolution to 1536x864 (HIDPI).

**Comment by ixkqo** [comment]
now only usb port customization

**Comment by IFierta** [comment]
> now only usb port customization

ports do not work?

**Comment by ixkqo** [comment]
usb3. 0 not 5g/s

**Comment by IFierta** [comment]
> usb3.0 not 5g/s

[USBPorts.kext.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5157529/USBPorts.kext.zip)

[SSDT-EC-USBX.aml.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5157536/SSDT-EC-USBX.aml.zip)
Try to use this kext and ssdt. Do not use SSDT-EC-USBX.aml and SSDT-EC.aml at the same time.

**Comment by IFierta** [comment]
> usb3.0 not 5g/s

[USBPorts.kext.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5157641/USBPorts.kext.zip)
Try to use this kext.

**Comment by ixkqo** [comment]
Can you give me a bios file in order to unlock cfg, because I can't extract it

**Comment by IFierta** [comment]
> Can you give me a bios file in order to unlock cfg, because I can't extract it，The bios version is 301

Do you have a BIOS flashing device? 
If you do not have a device for flashing a BIOS, then how will you flash a modified BIOS without a device for flashing a BIOS? If you have such a device, then you yourself can make a BIOS dump from your chip. Unfortunately, I do not have a BIOS dump. I didn't save it.


[Unlock 0xE2 MSR](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/wiki/Unlock-0xE2-MSR)
Read the article on how to unlock CFG without flashing BIOS.



`One Of: CFG lock, VarStoreInfo (VarOffset/VarName): 0x76, VarStore: 0x1, QuestionId: 0x5D, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 BE 02 BF 02 5D 00 01 00 76 00 10 10 00 01 00}
0x12A36 					One Of Option: Disabled, Value (8 bit): 0x0 {09 07 EF 01 00 00 00}
0x12A3D 					One Of Option: Enabled, Value (8 bit): 0x1 (default) {09 07 EE 01 30 00 01}
0x12A44 				End One Of {29 02}`

Your offset 0x76

> Enter setup_var 0x76 0x00 command, where 0x76 should be replaced by your actual offset and reboot.

**Comment by IFierta** [comment]
[ASUS K501L.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5160713/ASUS.K501L.zip)
I found this dump on one Russian technical forum. Use at your own risk.
