### ISSUE TITLE
hdmi

### ISSUE THREAD

**Issue by ixkqo** [IFierta/mac-os-opencore-asus-k501lx_lb#4]
HDMI work？ I don't have an HDMI cable

**Comment by IFierta** [comment]
I don't know, test it. In theory, it should work. I did everything necessary for HDMI to work. But I didn't check it.

**Comment by ixkqo** [comment]
I unlock cfg，offset also is  0x76

**Comment by IFierta** [comment]
Not. The same as in Windows. 
Change smbios to macbook air. Test it. If you will be using smbios macbook pro, remove and disable AGPM kext, this kext will underestimate the GPU frequency to 300 megahertz. This frequency is not enough for the MacBook Pro to work well.

**Comment by ixkqo** [comment]
Does the SSDT to add a judgment of an operating system type? I guided double system with OC

**Comment by IFierta** [comment]
Yes, SSDT are made with other operating systems in mind.

**Comment by ixkqo** [comment]
I customized this ssdt（SSDT-UIAC.aml） for usb, and I am not sure whether to add judgment on the operating system

**Comment by IFierta** [comment]
> I customized this ssdt（SSDT-UIAC.aml） for usb, and I am not sure whether to add judgment on the operating system，It is automatically generated by hackintool

Add method _STA to device.

```
Device (UIAC)
    {
         Method (_STA, 0, NotSerialized)  // _STA: Status
        {
            If (_OSI ("Darwin"))
            {
                Return (0x0F)
            }
            Else
            {
                Return (Zero)
            }
        }
}
```

**Comment by ixkqo** [comment]
thank you ，but what software is used to edit aml format files, I see that MaciASL is used to edit dsl files.

**Comment by IFierta** [comment]
> thank you ，but what software is used to edit aml format files, I see that MaciASL is used to edit dsl files.

Yes, maciasl.

Use the USBPorts kext. The SSDT-UIAC is made to be used with USBInjectAll. The SSDT contains a device named UIAC which isnt used by macos because it's not a usual device but a virtual one that only exists because USBInjectAll kext can use it.

Or use this script ( [USBMap](https://github.com/corpnewt/USBMap) to configure usb.

**Comment by ixkqo** [comment]
yes，usb 3.0 Already working

**Comment by ixkqo** [comment]
Is your usb not customized? I don’t see USBPorts and ssdt-UIAC files in your EFI file.

**Comment by IFierta** [comment]
> The SSDT-UIAC is made to be used with USBInjectAll. 

I will add kext later.

**Comment by ixkqo** [comment]
close csm，it’s  difficult to solve the screen becomes blurred and indistinct when boot up

**Comment by IFierta** [comment]
IOGraphicsFamily needs to be patched. But nobody wants to look for what needs to be patched, nobody needs it.

**Comment by ixkqo** [comment]
HDMI not work

**Comment by IFierta** [comment]
[config.plist.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5182946/config.plist.zip)
try this. let me know the result

**Comment by ixkqo** [comment]
I use your config file and directly use the HDMI interface to output HDMI to the external monitor. There is no signal conversion. When the progress bar is loaded, the external monitor works. However, when the progress bar ends and enters the system interface, the external monitor has a black screen and no signal. , This is my config file.
[config.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5200290/config.zip)

**Comment by IFierta** [comment]
[config.plist.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5200962/config.plist.zip)

i added force-online property to deviceproperties. try.
update opencore to version 0.6.1, look in my repository.

`igfxonln=1 boot argument (force-online device property) to force online status on all displays.`

**Comment by ixkqo** [comment]
not work，need  enter the system settings? not display as soon as boot

**Comment by IFierta** [comment]
[config.plist.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5201811/config.plist.zip)
try this config.
do you use a 4k monitor?

**Comment by ixkqo** [comment]
just 1366x768，this config Cannot enter the system.

**Comment by IFierta** [comment]
you updated opencore to version 0.6.1?

**Comment by IFierta** [comment]
[config.plist.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5202194/config.plist.zip)
config support opencore 0.6.0, try it

**Comment by IFierta** [comment]
if this does not work, then I will try to apply the binary patches again, if the binary patches do not help, then I will not be able to help anything else.

**Comment by ixkqo** [comment]
My version is still 0.6.0, it crashes when it is halfway loaded, and returns to the selection system interface, and a prompt appears before loading your computer due to a problem.

**Comment by ixkqo** [comment]
there are some prompt，Might help

If you don’t understand Chinese, you can use translation software, because my computer screen is broken and I can’t operate it. I can only trouble you.
   https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html

**Comment by IFierta** [comment]
> My version is still 0.6.0, it crashes when it is halfway loaded, and returns to the selection system interface, and a prompt appears before loading your computer due to a problem.

your system does not boot with a connected monitor or does not boot at all?

**Comment by ixkqo** [comment]
My system can be booted, but it cannot be displayed on the connected monitor,

**Comment by ixkqo** [comment]
If I change the computer screen to 1366x768 resolution, when I turn off csm, there should be no graphics failure when I turn on it.

**Comment by ixkqo** [comment]
Is the network card you replaced bcm943225hmb

**Comment by IFierta** [comment]
> If I change the computer screen to 1366x768 resolution, when I turn off csm, there should be no graphics failure when I turn on it.



> Is the network card you replaced bcm943225hmb


I do not know.

Yes, BCM94352HMB

**Comment by ixkqo** [comment]
How to make mac system boot first

**Comment by IFierta** [comment]
If I understand you correctly, you are wondering how to make the Mac OS boot first?
If so, then when the operating system selection menu appears, you need to press the key combination ctrl+enter.

**Comment by ixkqo** [comment]
After sleep, wake up to a black screen
