### ISSUE TITLE
下载下来才知道没有驱动

### ISSUE THREAD

**Issue by tnwss** [IFierta/mac-os-opencore-asus-k501lx_lb#5]
要哭了 同机型  下载之后才知道没有其他驱动

**Comment by IFierta** [comment]
Write in English, I don't know Chinese.
What driver is missing?

**Comment by tnwss** [comment]
kext There are only three

**Comment by IFierta** [comment]
> kext There are only three

To download kexts, use the download_kexts.sh script

**Comment by tnwss** [comment]
This script will not be used. Please give me some advice  download_kexts.sh

**Comment by IFierta** [comment]
[download_kexts.sh.zip](https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/files/5331133/download_kexts.sh.zip)
