### ISSUE TITLE
谢谢楼主的分享！

### ISSUE THREAD

**Issue by wenwei7532** [IFierta/mac-os-opencore-asus-k501lx_lb#7]
My computer model is v505lx and uses the shared EFI Mac OS Big Sur. Now it is found that the wake-up screen has backlight but no display.

**Comment by IFierta** [comment]
Display AU Optronics B156HTN03.8?

**Comment by wenwei7532** [comment]
After the test, there is still no image display after wake-up. The shortcut key setting can adjust the brightness of the screen, that is, no image is displayed. Led model auo38ed

**Comment by IFierta** [comment]
[https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/issues/3#issuecomment-683812474](url)

**Comment by wenwei7532** [comment]
I think it may have something to do with blocking independent graphics. Some people on the forum use "- wegnoegpu" to solve this problem. But Big Sur doesn't seem to support this command.

**Comment by IFierta** [comment]
"- wegnoegpu" - as far as I remember, boot arg "- wegnoegpu" did not work in other versions of mac os. For this reason I made a ssdt https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb/blob/master/Additional/src/acpi/SSDT-DDGPU.dsl

**Comment by IFierta** [comment]
I want to draw your attention to the fact that in Mac OS 10.12.3 there were no problems waking up the display. The problem has been present since version 10.12.4 and higher. Presumably the video driver is sending an unsupported mode to the display.
